---
- name: "Install Docker"
  hosts: "{{ variable_host | default('tag_docker_host') }}"
  become: true
  vars_files:
    - "credentials.yml"
  roles:
  - role: "nickjj.docker"
    tags: ["docker", "install"]
    docker__users: ["appuser", "k_syrovatsky"]
    docker__registries:
    - registry_url: "https://index.docker.io/v1/"
      username: "{{ username }}"
      password: "{{ password }}"
    docker__default_pip_packages:
    - name: "docker"
      state: "{{ docker__pip_docker_state }}"
