---
# tasks file for app
- name: "Run app container"
  docker_container:
    name: "reddit"
    image: "gidmaster/otus-reddit:1.0"
    ports:
      - "9292:9292"
  vars:
    ansible_python_interpreter: "/usr/bin/env python-docker"
