version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend 
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      - frontend
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - backend
      - frontend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  backend:
  frontend:
